version: '3'

services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - '9000:9000'
      - '8080:8080'
    volumes:
      - .:/src
    command: npm run start
    environment:
      - CHOKIDAR_USEPOLLING=1